### ISSUE TITLE
Rich Changelog with automatic release action

### ISSUE THREAD

**Issue by Shayan-Ghani** [siavash1991/xboard-react#1]
Hey @siavash1991 
I am quite impressed by your project I'd love to add automatic version bumping for it if you're down. However you must conform to semantic versioning rules when committing, for it to work !

let me know what you think

**Comment by Shayan-Ghani** [comment]
I walked through your project again and saw you're using npm and semantic release already, in that case I can help you build a better release with change log like the following release notes: 

https://github.com/devopshobbies/boundary-vault-stack/releases/tag/v0.8.3

**Comment by siavash1991** [comment]
Hi @Shayan-Ghani 

Thank you for your interest in my project and for your kind words! I’ve already configured Semantic Release for automatic versioning, but I’m always open to enhancements that can improve the release process, including richer changelogs.

I would be delighted to have you collaborate on this project. If you have specific ideas or improvements in mind, feel free to share them or open a pull request. Your expertise and suggestions are very welcome!

Looking forward to working together.
